server:
  tomcat:
    uri-encoding: UTF-8
  port: 8081

spring:
  application:
    name: open-book-search
  profiles:
    active: local

---

spring.profiles: local
spring:
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: test1234
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: hikari-cp
      maximum-pool-size: 20
      minimum-idle: 10
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    generate-ddl: false
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

logging:
  level:
    org.springframework: info
    com.yorath.booksearch: debug

# Open API Information
open-api:
  kakao:
    app-key: 2fcfd0d6690256bb06d549f1bafb8c73
    book-search-url: https://dapi.kakao.com/v3/search/book
  naver:
    client-id: Dz3nhi0Tz3i_QJDOEF2O
    client-secret: U6qerTT0GK
    book-search-url: https://openapi.naver.com/v1/search/book.json


